##### API SERVICES #####

services:

#    api.last_login_subscriber:
#        class: ApiBundle\EventListener\Security\LastLoginSubscriber
#        autowire: true
#        tags:
#            - { name: kernel.event_subscriber }

    api.jwt_token_authenticator:
        class: ApiBundle\Security\jwtTokenAuthenticator
        autowire: true

    api.encode_password_subscriber:
        class: ApiBundle\EventListener\Security\EncodePasswordSubscriber
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }

    api.canonicalizer_email_subscriber:
        class: ApiBundle\EventListener\Security\CanonicalizerEmailSubscriber
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }

    api.response_factory:
        class: ApiBundle\Api\ResponseFactory

    api.exception_subscriber:
        class: ApiBundle\EventListener\ApiExceptionSubscriber
        arguments: ['%kernel.debug%', '@api.response_factory']
        tags:
            - { name: kernel.event_subscriber }

    api.pagination_factory:
        class: ApiBundle\Pagination\PaginationFactory
        autowire: true

    api.custom_hateoas_json_serializer:
        class: ApiBundle\Serializer\CustomHATEOASJsonSerializer

    api.link_serialization_subscriber:
        class: ApiBundle\Serializer\LinkSerializationSubscriber
        autowire: true
        tags:
            - { name: jms_serializer.event_subscriber }

    api.ffmpeg:
        class: ApiBundle\FFmpeg\FFmpeg
        arguments: ['@monolog.logger', '%ffmpeg%']

    api.custom_video_image_namer_vich_upload:
        class: ApiBundle\VichUpload\CustomVideoImageNamer

    api.custom_video_dir_namer_vich_upload:
        class: ApiBundle\VichUpload\CustomVideoDirNamer