api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /api/
    defaults:
        #_format: json

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"


