<?php

namespace ApiBundle\Repository;

use ApiBundle\Entity\Video;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends BaseRepository
{
    /**
     * @param array $params
     * @param Video $video
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function findAllQueryBuilder($params = [], $video = null)
    {
        $qb = $this->createQueryBuilder('comment')
            ->select('comment');

        if (isset($params['filter']) && !empty($params['filter'])) {
            $qb->innerJoin('comment.video', 'video')
                ->addSelect('video');
            $qb->andWhere('video.title LIKE :filter')->setParameter('filter', '%' . $params['filter'] . '%');
        }

        if (!is_null($video)) {
            $qb->andWhere('comment.video = :video')->setParameter('video', $video);
        }

        $this->addOrderingQueryBuilder($qb, $params);

        return $qb;
    }
}
