<?php

namespace ApiBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * @param string $filter
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function findAllQueryBuilder($filter = '')
    {
        $qb = $this->createQueryBuilder('user');

        if ($filter) {

            $qb->andWhere(
                $qb->expr()->like(
                    $qb->expr()->concat('user.firstName', $qb->expr()->concat($qb->expr()->literal(' '), 'user.lastName')),
                    ':filter'
                )
            )->setParameter('filter', '%' . $filter . '%');
        }

        return $qb;
    }
}
