<?php

namespace ApiBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends BaseRepository
{
    /**
     * @param array $params
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function findAllQueryBuilder($params = [])
    {
        $qb = $this->createQueryBuilder('user');

        if (isset($params['filter']) && !empty($params['filter'])) {
            $qb->andWhere(
                $qb->expr()->like(
                    $qb->expr()->concat('user.firstName', $qb->expr()->concat($qb->expr()->literal(' '), 'user.lastName')),
                    ':filter'
                )
            )->setParameter('filter', '%' . $params['filter'] . '%');
        }

        $this->addOrderingQueryBuilder($qb, $params);

        return $qb;
    }
}
