<?php

namespace ApiBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * VideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRepository extends EntityRepository
{
    /**
     * @param string $filter
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function findAllQueryBuilder($filter = '')
    {
        $qb = $this->createQueryBuilder('video');

        if ($filter) {
            $qb->andWhere('video.title LIKE :filter')->setParameter('filter', '%' . $filter . '%');
        }

        return $qb;
    }
}
