<?php

namespace ApiBundle\Repository;

use ApiBundle\Entity\User;

/**
 * VideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRepository extends BaseRepository
{
    /**
     * @param array $params
     * @param User $user
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function findAllQueryBuilder($params = [], $user = null)
    {
        $qb = $this->createQueryBuilder('video');

        if (isset($params['filter']) && !empty($params['filter'])) {
            $qb->andWhere('video.title LIKE :filter')->setParameter('filter', '%' . $params['filter'] . '%');
        }

        if (!is_null($user)) {
            $qb->andWhere('video.user = :user')->setParameter('user', $user);
        }

        if (isset($params['offset']) && !empty($params['offset'])) {
            $qb->andWhere('video.id <> :id')->setParameter('id', $params['offset']);
        }

        $this->addOrderingQueryBuilder($qb, $params);

        return $qb;
    }

    /**
     * @param $id
     * @return \Doctrine\ORM\QueryBuilder
     * @internal param array $params
     */
    public function findLastsQueryBuilder($id)
    {
        $qb = $this->createQueryBuilder('video')
            ->andWhere('video.id <> :id')->setParameter('id', $id)
            ->orderBy('video.createdAt', 'DESC');

        return $qb->getQuery()->getResult();
    }
}
